version: '3.7'
services:
  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    # network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - selenoid-net

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    container_name: selenoid-ui
    # network_mode: bridge
    environment:
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    links:
      - selenoid
    # ports:
    #   - "8080:80"
    expose:
      - 80
    command: ["--selenoid-uri", "http://selenoid:4444", "--listen", ":80"]
    networks:
      # - webproxy
      - selenoid

  selenoid-chrome:
    image: selenoid/chrome:latest
    container_name: selenoid-chrome
    # network_mode: bridge
    networks:
      - selenoid-net

  selenoid-firefox:
    image: selenoid/firefox:latest
    container_name: selenoid-firefox
    # network_mode: bridge
    networks:
      - selenoid-net

networks:
  selenoid:
    driver: bridge
  webproxy:
    external:
      name: webproxy
